### ISSUE TITLE
A problem about the teacher-student model

### ISSUE THREAD

**Issue by JNZZZ** [SmiletoE/HPAL#10]
﻿I am appreciate for your awesome work. 
In your paper, you use a teacher-student model to produce extra supervision signal. But in it's original paper, the teacher model is generally used as the final prediction model. In your code, it seems that you use the student model to do the final prediction. Am I missing some important points while reading the code OR you have some other reasons to use the student model?

**Comment by SmiletoE** [comment]
In our paper, we only build a rough teacher-student model to utilize unlabelled data in combination with the proposed active learning method, and do not optimize the training parameters and details. The student model is used in the final prediction only because it can show good results, without any special consideration. However, to realize an in-depth combination of active learning and semi-supervised learning, how to better utilize the prediction of the teacher-student model for active selection is also a topic worthy of further study.
